name: inventoryapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.1
  image_picker: ^0.8.4+4
  provider: ^6.0.2
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
